%f=imread('./imagenes/picassobw_red.jpg');
%f=double(f);
[m,n]=size(f);
%fn=imnoise2('Gaussian',m,n,0,sqrt(0.01));
%phantom=checkboard
F=fft2(f);
Fc=fftshift(F);
Fcc=log(1+abs(Fc));
FN=fft2(fn);
FNc=fftshift(FN);
FNcc=log(1+abs(Fc));

S=abs(F);
figure(1)
subplot(1,2,1)
imshow(f,[])
subplot(1,2,2)
imshow(Fcc,[])
figure(2)
subplot(1,2,1)
imshow(fn,[])
subplot(1,2,2)
imshow(FNcc,[])